project_id = "amwewckftjeahzsktcqp"

[functions.google-sheets]
verify_jwt = false

[functions.validate-payout-token]
verify_jwt = false

[functions.submit-public-payout]
verify_jwt = false

[functions.check-pending-payouts]
verify_jwt = false

[functions.add-images-to-payout]
verify_jwt = false
